{"uuid": "613c83e1-7783-469b-a71a-0a4fc040435c", "children": ["9eedfd43-f095-4fa3-96f4-62cb0d1732ac", "f1b1849f-d4ff-4d81-8865-bc8d759ce999", "f48c31c0-5794-44da-a1bd-b7427b7ea715", "97aa1092-f134-4833-bd57-e02011351bd9"], "befores": [{"name": "xunit_setup_class_fixture_TestUserLogin", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test_user_data.xlsx'\n", "trace": "  File \"C:\\soft\\anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\soft\\pycharm\\pythonProject\\test2\\request\\test_ydy\\test_login.py\", line 19, in setup_class\n    self.data_list = excel_to_list(\"test_user_data.xlsx\", \"TestUserLogin\")\n  File \"D:\\soft\\pycharm\\pythonProject\\test2\\request\\read_excel.py\", line 6, in excel_to_list\n    wb = xlrd.open_workbook(data_file)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\xlrd\\__init__.py\", line 111, in open_workbook\n    with open(filename, \"rb\") as f:\n"}, "start": 1615181942964, "stop": 1615181942964}], "start": 1615181942964, "stop": 1615181943264}