{"uuid": "2249d7fc-0ffa-4393-8e6c-817d7d47ca24", "children": ["65a5455f-34ee-470d-8e66-be5b1ad1b04d", "5b9c81b6-93f9-49db-b373-4d1f30a42e76", "f1a45c32-7159-4f6b-9fdc-6aea99344356", "99eb56f0-7a48-4bd2-96c3-1af43b5fc99a"], "befores": [{"name": "xunit_setup_class_fixture_TestUserLogin", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'test_user_data.xlsx'\n", "trace": "  File \"C:\\soft\\anaconda3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\soft\\pycharm\\pythonProject\\test2\\request\\test_ydy\\test_login.py\", line 19, in setup_class\n    self.data_list = excel_to_list(\"test_user_data.xlsx\", \"TestUserLogin\")\n  File \"D:\\soft\\pycharm\\pythonProject\\test2\\request\\read_excel.py\", line 6, in excel_to_list\n    wb = xlrd.open_workbook(data_file)\n  File \"C:\\soft\\anaconda3\\lib\\site-packages\\xlrd\\__init__.py\", line 111, in open_workbook\n    with open(filename, \"rb\") as f:\n"}, "start": 1615182139686, "stop": 1615182139686}], "start": 1615182139686, "stop": 1615182139994}