{"name": "test_qlogin_normal", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'encode'", "trace": "self = <test_login.TestUserLogin object at 0x00000232930E2C40>\n\n    def test_qlogin_normal(self):\n        case_data = get_test_data(self.data_list, \"test_qlogin_normal\")\n        if not case_data:  # 有可能为None\n            logging.error(\"用例数据不存在\")\n    \n        url = case_data.get('url')\n        data = json.loads(case_data.get('data'))\n        expect_res = case_data.get('expect_res')\n    \n        res = requests.post(url=url, json=data, verify=False)\n        assert res.json()['code'] == expect_res\n        # print(f\"验证码登录成功： {res.reason}\")\n        logging.info(\"验证码登录成功：{}\".format(res.reason))\n    \n>       res_text = res.json().encode()\nE       AttributeError: 'dict' object has no attribute 'encode'\n\ntest_login.py:36: AttributeError"}, "attachments": [{"name": "log", "source": "85662aaa-f58d-4d81-9cf0-ab892bda3dbc-attachment.txt", "type": "text/plain"}], "start": 1614933501774, "stop": 1614933501954, "uuid": "8bdbdb2b-68fe-4aa3-9309-253e248e553a", "historyId": "415ce8af72144b8e2e2a2835b3d3e60d", "testCaseId": "0210d8c0eab07c4329b10bb4c3919f81", "fullName": "test_login.TestUserLogin#test_qlogin_normal", "labels": [{"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "liailian"}, {"name": "thread", "value": "31208-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}