{"name": "test_user_reg_normal", "status": "broken", "statusDetails": {"message": "NameError: name 'data_list' is not defined", "trace": "self = <test_register.TestUserRegister object at 0x000001E8899C7E50>\n\n    def test_user_reg_normal(self):\n>       case_data = get_test_data(data_list, 'test_user_reg_normal')\nE       NameError: name 'data_list' is not defined\n\ntest_register.py:21: NameError"}, "start": 1614927050542, "stop": 1614927050543, "uuid": "7372df88-acbf-48cd-afe4-9b5a2d6af2e0", "historyId": "8259e7a8b45919af77c6c4bdf0cb0bf3", "testCaseId": "678e3f0c363742129983853f14af8594", "fullName": "test_register.TestUserRegister#test_user_reg_normal", "labels": [{"name": "suite", "value": "test_register"}, {"name": "subSuite", "value": "TestUserRegister"}, {"name": "host", "value": "liailian"}, {"name": "thread", "value": "20124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_register"}]}